version: "3.9"
services:
  # Kafka
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    logging:
      driver: "none"
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  # Data producers
  data_producer_eth:
    build:
      context: ./src/data_producer
    profiles: ["eth"]
    depends_on:
      - kafka

  data_producer_etc:
    build:
      context: ./src/data_producer
    profiles: ["etc"]
    depends_on:
      - kafka

  data_producer_bsc:
    build:
      context: ./src/data_producer
    profiles: ["bsc"]
    depends_on:
      - kafka

  # Transaction consumers

# Kafka related config
# see: https://github.com/bitnami/bitnami-docker-kafka/blob/a576f9847c9ed455645d6540a7f32e7935e6b4d7/docker-compose.yml#L24
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local