name: Publish Docker images
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    name: Build and push Docker images to GitHub Container Registry
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./src/data_collection/Dockerfile
            image: ${{ env.REGISTRY }}/uzh-eth-mp/data_collector
          - dockerfile: ./src/db/Dockerfile
            image: ${{ env.REGISTRY }}/uzh-eth-mp/db
          - dockerfile: ./src/kafka/Dockerfile
            image: ${{ env.REGISTRY }}/uzh-eth-mp/kafka
          - dockerfile: ./src/zookeeper/Dockerfile
            image: ${{ env.REGISTRY }}/uzh-eth-mp/zookeeper
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker images
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
